apiVersion: v1
kind: Service
metadata:
  name: subscribermanagement
  labels:
    app: subscribermanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: subscribermanagement