apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmanagement
  labels:
    app: bookmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmanagement
  template:
    metadata:
      labels:
        app: bookmanagement
    spec:
      containers:
        - name: bookmanagement
          image: "username/bookmanagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
